### ISSUE TITLE
C++ (and it's implementations) reffer(s) to mid-level/pseudo low-level languages so not actually low-level

### ISSUE THREAD

**Issue by ghost** [robertmuth/awesome-low-level-programming-languages#10]
You can check more here: 
https://www.tuple.nl/blog/all-you-need-to-know-about-low-level-languages
https://www.coursereport.com/blog/a-guide-to-low-level-programming-for-beginners

**Comment by robertmuth** [comment]
Sure C++ is a borderline case but it does have manual memory management and has been used to write OSes so I will keep it on the list.

**Comment by ghost** [comment]
Java was also used to write OSes, that's won't make it a low-level programming language.

Trimis cu Proton Mail pentru Android

-------- Mesaj original --------
16.05.2024 18:35, Robert Muth  a scris:
