### ISSUE TITLE
chore: ambiguity in definition of low level language

### ISSUE THREAD

**Issue by dzmitry-lahoda** [robertmuth/awesome-low-level-programming-languages#11]
From readme:
```md
**Excluded are languages relying on managed run-times and without manual memory management.**
```
C# has MMM(like Rust unsafe + some references), it has GC, it has AOT of time compile. For example C# has modules compiled for C++ consumption by its JIT and by UEFI.

For inclusion listed:
```
[Roc](https://www.roc-lang.org/),
```
Roc has GC, has no MMM, but it is AOT compiled. So it must not be included.

So not clear what you mean by managed run-time?

I propose next inclusion criteria:
```
Languages inclusion is not considered if  summary of these states are mostly true:
- AOT native target compiler is not default main target. JIT or interpreted only languages are excluded.
- Default  coding style produces binaries which has friction to be called and consumed by other MMM languages. GC and green threads are typical examples of friction.
- MMM can be done only via unsafe or without default coding style language abstractions
```

With these C# and Roc will not be included.

With original definition C# must be included (it runs in UEFI and also AOT compiled for consumtion by JIT written in C++.

Also C# is very popular in games, and some OS written in C# too :) .

**Comment by robertmuth** [comment]
I just updated the doc and dropped roc.
having a GC is incompatible with my understanding of a low level language. 

I have not looked in detail at OSes written in languages with a non optional GC but they tend to be experimental and I bet a non trivial part of the OS cannot be expressed in the language itself and had to be written in C
