### ISSUE TITLE
Cone highlights and Fibonacci

### ISSUE THREAD

**Issue by jondgoodwin** [robertmuth/awesome-low-level-programming-languages#4]
Please update Cone entry...

Highlights:

  - Regions for memory management versatility/safety
  - Permissions for thread versatility/safety
  - Delegated inheritance and structural subtyping
  - Variant types (three flavors)
  - Actors
  - Generic functions, types and modules

Fibonacci example

// Fibonacci

import stdio::*

fn fib(n i64) i64:
  mut prior i64 = 0
  mut result i64 = 1
  while n-- > 0:
    prior, result = result, prior + result
  result

fn main():
  print <- fib(6)

**Comment by robertmuth** [comment]
I added most of your suggestion. As I mentioned on reddit, one of the objectives is to enable comparisons across languages.
So I held back with a few features. One area that I now feel deserves its own entry is "memory/lifetime management".

Since you have given this a lot more thought than I have, do you have some suggestions in this regard?
I do not expect a full-blown taxonomy but what are some "bullets" that make sense here.
Some things that come to mind are
* arc
* arenas
* smart pointers
* borrow checker (maybe some verbiage since the design space is larger than RUST's flavor)

How do cone's regions and permissions fit in here

**Comment by jondgoodwin** [comment]
Hi Robert, This is your list and I respect your right to characterize the languages however you want, so your decision is final.

That said, I am not clear on why you do not want to highlight the features that make a language distinctive, especially when no other language supports a similar capability.  When I look at new languages, that is literally the first thing I look for:  what are they doing that is interesting and different?

Cone's "Regions for memory management versatility/safety" encompasses a capability that no other language offers:  the ability to define and use multiple memory management strategies within a single language:  arc, arenas, tracing GC, pool, single-owner and many varieties of the same. If you twist your head sideways, Rust offers a far more limited version of this capability, but it severely cripples what is possible with arenas, pools and tracing GC. The point is they are not hard-coded into the language, they are importable library capabilities deeply facilitated by the language in a way no one has done before. So, if you want to tweak the description you can add to it:  "Regions for safe, versatile memory management:  single-owner, rc, arena, pool and tracing gc".  I was just trying to keep it brief and intriguing. 

Cone does support a more versatile borrow checker and lifetime capability than Rust: borrowed references may be shared mutable and lifetimes can be invariants.  You are welcome to add this bullet.

"Permissions for thread versatility/safety" is another feature found in few other languages:  Pony calls them reference capabilities. M# had a subset.  Rust distinguishes between & vs. &mut. Permissions are entirely separate from memory management (regions), and are focused on eliminating race safety issues.  Like regions, permissions are found on all references.

"Delegated inheritance and structural subtyping"  Delegated inheritance is another feature found in no other language. You can find a sort of subset of this capability in Go and D, but those are missing a lot. Many other languages support inheritance, but it is a very different flavor than delegated inheritance.  As for structural subtyping, nearly all languages use nominal subtyping. Go and Pony are two exceptions that also support structural subtyping.

"Variant types (three flavors)"  I added the three flavors, because nearly all languages offer only one:  typically either sum types or OOP inheritance. Cone offers both in a more powerful form and then adds a third in between.


Also, you have added two comments I don't know where you get them from:

"Immutable by Default"  This gets to permissions. Immutable is not the default permission.  What Cone does is ask you to specify per variable or reference, which permission you want:  immutable, mutable, unique, etc. It is not accurate to say immutable is the default permission.

"indentation matters". I would say indentation CAN matter.  Cone is the rare language that allows you to use either free-form (indentation does not matter but use curly braces for blocks) and Python-like offside (start the block with a : and then following lines need to be indented)

**Comment by robertmuth** [comment]
Hi Jon,

sorry about misrepresenting the mutability indentation part, I just looked at the fib example and made an educated guess.
(I hopefully fixed that in the last commit).

My concerns with "Regions for memory management versatility/safety"  and  "Permissions for thread versatility/safety"
was that
1) they are a bit vague 
2) "permission" is not a common term in the PL world

These could be addressed by links with clarifications. I have not done this for the other languages but I willing to try.
I looked at your documentation. Are there some links you can commit to keep stable for this purpose. 

BTW:  I almost missed the cone reference section since the pages discussing  the design goals do not link back to it.

**Comment by jondgoodwin** [comment]
Hi Robert,

When you say my some of my highlights feel vague, I sympathize with that. I have not figured out how to distill ideas that people have never encountered before into a few words and expect them to be grasped instantly. I am always open to feedback on my choice of words. The chosen words "region" and "permission" are not well known, but there are known to experts and they narrow down the semantic intent for those people.

I agree that links would be really handy, and if you are willing to support them, I will put some together.

I am in the middle of doing a refurbishment of the reference and summary pages, so let me add this to that list, and I will get back to you when they are ready. This will include having links to the reference pages in the design goal pages.

Appreciate your feedback and flexibility here.

**Comment by robertmuth** [comment]
SGTM  

BTW: Maybe this comes in handy for contrasting the various approaches for capabilities/permissions:

https://uu.diva-portal.org/smash/get/diva2:1363822/FULLTEXT01.pdf

**Comment by jondgoodwin** [comment]
Thanks for that link. I remember reading it from just after she got it published. It is pretty exhaustive in a narrow sense.

I was already familiar with Rust and Pony, of course, but Encore (and its somewhat different approach) was new to me. Pony's reference capabilities were actually inspired by M# permissions (for the Midori project). And Cone's are a superset of Pony and Rust permissions.

I discuss Cone's permissions in my blog post starting here:  https://pling.jondgoodwin.com/post/race-safe-strategies/ and if you look at the bottom of this post you will see where I compare the names of permissions across Rust, Pony, Midori, and Cone. 

So, yup that is the heritage for what Cone calls permissions. They have a heritage, but most people are unfamiliar with it.

**Comment by jondgoodwin** [comment]
Hi Robert, as requested, I have taken the time to create stable links for exactly these points. Take a look at the revised [home page](https://cone.jondgoodwin.com/), particularly the four bullets underneath "Distinctive Features".  Each of these takes you to a full page that distills information about these features. Those pages in turn have links to the appropriate pages in the Cone reference documentation. Lots of room to become curious and learn all about it.

Feel free to reproduce these four bullets in your repo entry for Cone, if you think it will add value to you and your users.
