### ISSUE TITLE
Val is getting renamed to Hylo

### ISSUE THREAD

**Issue by zaits07** [robertmuth/awesome-low-level-programming-languages#9]
val-lang
https://github.com/robertmuth/awesome-low-level-programming-languages#val
renamed to hylo

citate from https://github.com/hylo-lang/hylo
"Warning. Val is getting renamed to Hylo. We apologize for any broken links and confusion this may cause. We're working on it."

new links:
https://www.hylo-lang.org
https://github.com/hylo-lang/hylo

**Comment by robertmuth** [comment]
fixed
